---
title: "nutrient_analysis"
author: "Liyenne"
date: "2024-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, include = FALSE}
se <- function(x) sd(x)/sqrt(length(x))

# wrangling
require(readxl)
require(tidyverse)

# visualizing
require(ggplot2)

# analyzing
require(fitdistrplus)
require(lme4)
require(lmerTest)

require(DHARMa)
require(easystats)

require(lsmeans)
require(emmeans)
```

```{r read data, echo = FALSE}
# c/n
chem_data <- read.csv("../../2_input/1_raw_data/chem/chem_malla_soil_leaves.csv")
head(chem_data)

cn_soil <- chem_data %>% 
  filter(type == "soil") %>% 
  filter(comment != "broken capsule") %>% 
  mutate(transect_ID = paste(country, transect, sep = "")) %>% 
  dplyr::select(Sample_ID, country, transect, transect_ID, everything())

cn_leaf <- chem_data %>% 
  filter(type == "leaf") %>% 
  filter(comment != "broken capsule") %>% 
  mutate(transect_ID = paste(country, transect, sep = "")) %>% 
  dplyr::select(Sample_ID, country, transect, transect_ID, everything())

# nitrate, ammonium, phosphate
dnp <- read_excel("../../2_input/1_raw_data/chem/DNP.xlsx") %>% 
  mutate(country = as.factor(ifelse(grepl('N', code), 'Storfjord', 'Malla')))
```

### Soil 
#### Carbon & Nitrogen
##### C/N ratio
```{r soil C/N ratio boxplot, echo = FALSE}
cn_soil %>% 
  ggplot(aes(x = habitat, y = CN_ratio, fill = country)) +
  geom_boxplot()
```

```{r soil C/N ratio distribution, echo = FALSE}
dist <- fitdist(cn_soil$CN_ratio, "norm")
plot(dist)
```

```{r soil LMM C/N ratio, echo = FALSE}
fit <- lmer(CN_ratio ~ country * habitat + (1|transect_ID), data = cn_soil) # 

summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r soil LMM C/N ratio model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(CN_ratio ~ country + habitat + (1|transect_ID), data = cn_soil)
check_model(fit)
x <- check_collinearity(fit)
plot(x); rm(x)
```

```{r soil LMM C/N ratio pairwise, echo = FALSE}
emmeans(fit, pairwise ~ country | habitat)$contrasts #???
```

##### % carbon
```{r soil carbpm boxplot, echo = FALSE}
cn_soil %>% 
  ggplot(aes(x = habitat, y = wC, fill = country)) +
  geom_boxplot()
```

```{r soil LMM % carbon, echo = FALSE}
dist <- fitdist(cn_soil$wC, "norm")
plot(dist)

fit <- lmer(wC ~ country * habitat + (1|transect_ID), data = cn_soil)

summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r soil LMM % carbon model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(wC ~ country + habitat + (1|transect_ID), data = cn_soil)
x <- check_collinearity(fit)
plot(x); rm(x)
```

##### delta13C
```{r soil d13C boxplot, echo = FALSE}
cn_soil %>% 
  ggplot(aes(fill = country, x = habitat, y = d13C)) +
  geom_boxplot()
```

```{r soil LMM delta 13C, echo = FALSE}
dist <- fitdist(cn_soil$d13C, "norm")
plot(dist)

fit <- lmer(d13C ~ country * habitat + (1|transect_ID), data = cn_soil) 

summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r soil LMM delta 13C pairwise comparisons, echo = FALSE}
emmeans(fit, pairwise ~ habitat)$contrasts
```

```{r soil LMM delta 13C model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(d13C ~ country + habitat + (1|transect_ID), data = cn_soil)
x <- check_collinearity(fit)
plot(x); rm(x)
```

##### % nitrogen
```{r soil nitrogen boxplot, echo = FALSE}
cn_soil %>% 
  ggplot(aes(x = habitat, y = wN, fill = country)) +
  geom_boxplot()
```

```{r soil LMM nitrogen, echo = FALSE}
dist <- fitdist(cn_soil$wN, "norm")
plot(dist)

fit <- lmer(wN ~ country * habitat + (1|transect_ID), data = cn_soil)

summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r soil LMM % nitrogen model  diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(wN ~ country + habitat + (1|transect_ID), data = cn_soil)
x <- check_collinearity(fit)
plot(x); rm(x)
```

##### delta15N
```{r soil d15N boxplot, echo = FALSE}
cn_soil %>% 
  ggplot(aes(x = habitat, y = d15N, fill = country)) +
  geom_boxplot() 
```

```{r soil LMM d15N, echo = FALSE}
dist <- fitdist(cn_soil$d15N, "norm")
plot(dist)

fit <- lmer(d15N ~ country * habitat + (1|transect_ID), data = cn_soil)

summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r soil LMM d15N pairwise comparisons, echo = FALSE}
lsmeans(fit, pairwise ~ habitat, lmer.df = "Satterthwaite", adjust = "tukey")$contrasts

emmeans(fit, pairwise ~ habitat)$contrasts
emmeans(fit, pairwise ~ country | habitat)$contrasts
```
```{r soil LMM d15N model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(d15N ~ country + habitat + (1|transect_ID), data = cn_soil)
x <- check_collinearity(fit)
plot(x); rm(x)
```

#### Mineralized nutrients
##### Phosphate (PO4)
```{r phosphate boxplot, echo = FALSE}
dnp %>% 
  na.omit() %>% 
  ggplot(aes(x = Habitat, y = PO4_corrected, fill = country)) +
  geom_boxplot() 
```

```{r phosphate LMMM, echo = FALSE}
dist <- fitdist(dnp$PO4_corrected, "lnorm")
plot(dist)

#fit <- lme(log(PO4_corrected) ~ country * Habitat, random = ~ 1 | ID, data =  #dnp, na.action = na.omit) 
fit <- lmer(log(PO4_corrected) ~ country * Habitat + (1|ID), data = dnp, na.action = na.omit)
summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r phosphate LMM pairwise comparisons, echo = FALSE}
emmeans(fit, pairwise ~ Habitat)$contrasts
emmeans(fit, pairwise ~ country | Habitat)$contrasts
```

```{r phosphate LMM model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(log(PO4_corrected) ~ country + Habitat + (1|ID), data = dnp, na.action = na.omit)
x <- check_collinearity(fit)
plot(x); rm(x)
```

##### Ammonium (NH4)
```{r ammonium boxplot, echo = FALSE}
dnp %>% 
  na.omit() %>% 
  ggplot(aes(x = Habitat, y = NH4, fill = country)) +
  geom_boxplot()
```

```{r ammonium LMM, echo = FALSE}
dist <- fitdist(dnp$NH4, "norm")
plot(dist)

fit <- lmer(NH4 ~ country * Habitat + (1|ID), data = dnp, na.action = na.omit)
summary(fit)
car::Anova(fit, test.statistic = "F")
```

```{r ammonium LMM pairwise comparisons, echo = FALSE}
emmeans(fit, pairwise ~ Habitat)$contrasts
emmeans(fit, pairwise ~ country | Habitat)$contrasts
```

```{r ammonium LMM model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(NH4 ~ country + Habitat + (1|ID), data = dnp, na.action = na.omit)
x <- check_collinearity(fit)
plot(x); rm(x)
```

##### Nitrate (NO3)
```{r, echo = FALSE}
dnp %>% 
  na.omit() %>% 
  ggplot(aes(x = Habitat, y = NO3, fill = country)) +
  geom_boxplot()
```

```{r, echo = FALSE}
dist <- fitdist(dnp$NO3, "lnorm")
plot(dist)

fit <- lmer(log(NO3) ~ country * Habitat + (1|ID), data = dnp, na.action = na.omit)
summary(fit)
car::Anova(fit, test.statistic = "F")
```
```{r soil LMM d15N diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

fit <- lmer(log(NO3) ~ country + Habitat + (1|ID), data = dnp, na.action = na.omit)
x <- check_collinearity(fit)
plot(x); rm(x)
```

### Tree leaves
##### C/N ratio
```{r leaf C/N ratio boxplot, echo = FALSE}
cn_leaf %>% 
  ggplot(aes(y = CN_ratio, fill = country)) +
  geom_boxplot()
```

```{r leaf LMM C/N ratio, echo = FALSE}
dist <- fitdist(cn_leaf$CN_ratio, "norm")
plot(dist)

fit <- lmer(CN_ratio ~ country + (1 | transect_ID), data = cn_leaf)
car::Anova(fit, test.statistic = "F")
```

```{r leaf LMM C/N ratio diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)
```

##### % carbon
```{r leaf carbon boxplot, echo = FALSE}
cn_leaf %>% 
  ggplot(aes(fill = country, y = wC)) +
  geom_boxplot()
```

```{r leaf LMM carbon, echo = FALSE}
dist <- fitdist(cn_leaf$wC, "norm")
plot(dist)

fit <- lmer(wC ~ country + (1 | transect_ID), data = cn_leaf)
car::Anova(fit, test.statistic = "F")
```

```{r leaf LMM carbon model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)
```

##### delta13C
```{r leaf d13C boxplot, echo = FALSE}
cn_leaf %>% 
  ggplot(aes(fill = country, y = d13C)) +
  geom_boxplot()
```

```{r leaf LMM d13C, echo = FALSE}
dist <- fitdist(cn_leaf$d13C, "norm")
plot(dist)

fit <- lmer(d13C ~ country + (1 | transect_ID), data = cn_leaf)
car::Anova(fit, test.statistic = "F")
```

```{r leaf LMM d13C model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)
```

##### % nitrogen
```{r leaf nitrogen boxplot, echo = FALSE}
cn_leaf %>% 
  ggplot(aes(fill = country, y = wN)) +
  geom_boxplot()
```

```{r leaf LMM nitrogen, echo = FALSE}
dist <- fitdist(cn_leaf$wN, "norm")
plot(dist)

fit <- lmer(wN ~ country + (1 | transect_ID), data = cn_leaf)
car::Anova(fit, test.statistic = "F")
```

```{r leaf LMM nitrogen model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)
```

##### delta15N
```{r leaf d15N boxplot, echo = FALSE}
cn_leaf %>% 
  ggplot(aes(fill = country, y = d15N)) +
  geom_boxplot()
```

```{r leaf LMM d15N, echo = FALSE}
dist <- fitdist(cn_leaf$d15N, "norm")
plot(dist)

fit <- lmer(d15N ~ country + (1 | transect_ID), data = cn_leaf)
car::Anova(fit, test.statistic = "F")
```

```{r leaf LMM d15N model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)
```
