---
title: "dung_data_analysis"
author: "Liyenne"
date: "2023-09-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

```{r include = FALSE} 
require(tidyr)
require(dplyr)
require(ggplot2)

require(fitdistrplus)
require(lme4)
require(glmmTMB)
require(emmeans)
require(DHARMa)
require(easystats)
```

# Data
**raw dung counts**
```{r echo = FALSE}
dung_count <- readr::read_csv('../../2_input/2_data_products/dung_count_data.csv')

dung_count %>% head(10)
```

**transect summary data**
```{r echo = FALSE}
dung_transect_data <- readr::read_csv('../../2_input/2_data_products/dung_data_transect_summary.csv')

dung_transect_data <- dung_transect_data %>% 
  mutate(country = as.factor(ifelse(grepl('N', transect), 'Storfjord', 'Malla'))) %>%
  dplyr::select(transect, country, everything())

dung_transect_data %>% head(10)
```

# Plotting
**dung frequencies**
```{r}
dung_transect_data$country <- factor(dung_transect_data$country, levels = c("Storfjord", "Malla"))

dung_transect_data %>%
  ggplot(aes(section, frequency, fill = country)) + 
  geom_boxplot() + 
  geom_jitter(aes(), alpha = 0.3, position = position_jitterdodge(jitter.width = 0, dodge.width = 0.75)) +
  theme_classic() +
  labs(fill = "Grazing regime", x = "Habitat", y = "Dung count") +
  scale_fill_manual(values = c("#77BFBC", "#EB956A"), labels = c("Winter", "Year-round")) +
  theme(panel.spacing = unit(.0, "lines"),
        panel.border = element_rect(color = "black", fill = NA, size = 1), 
        strip.background = element_rect(color = "black", size = 1),
        axis.text.x = element_text(angle = 45, hjust = 1), 
        )

ggsave("../../3_output/2_graphs/dung_counts.svg", height = 4, width = 2.85)
```
**total dung found**
```{r}
dung_transect_data %>%
  ggplot(aes(section, total_dung, fill = country)) + 
  geom_boxplot() 
```

```{r seedling count distribution, echo = FALSE}
dist <- fitdist(dung_transect_data$total_dung, "nbinom")
plot(dist)
```

```{r number of seedlings model}


# failed to converge
fit <- glmer.nb(total_dung ~ country * section + (1 | transect), data = dung_transect_data) 
fit <- glm.nb(n ~ country * section, data = d); AIC(fit)
fit <- glmmTMB(frequency ~ country * section + (1 | transect), 
               family = nbinom2, ziformula = ~1, 
               data = dung_transect_data) ; AIC(fit)

summary(fit)
anova(fit)
Anova(fit, type = "II")
```

```{r}
emmeans(fit, pairwise ~ country | section)
```

```{r seedlings model diagnostics}
simulationOutput <- simulateResiduals(fittedModel = fit)
plot(simulationOutput)
testDispersion(simulationOutput); rm(simulationOutput)

check_zeroinflation(fit)

fit <- glmer.nb(n ~ country + section + (1 | transect), data = d)
x <- check_collinearity(fit)
plot(x); rm(x)
```

```{r}
dung_transect_data %>% 
  #group_by(country, section) %>% 
  group_by(country) %>% 
  summarize(mean_count = mean(total_dung), se = SE(total_dung))
```

